/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_coccoc_Tokenizer */

#ifndef _Included_com_coccoc_Tokenizer
#define _Included_com_coccoc_Tokenizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_coccoc_Tokenizer
 * Method:    segmentJson
 * Signature: (Ljava/lang/String;ZIZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_coccoc_Tokenizer_segmentJson
  (JNIEnv *, jobject, jstring, jboolean, jint, jboolean);

/*
 * Class:     com_coccoc_Tokenizer
 * Method:    initialize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_coccoc_Tokenizer_initialize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
